BEGIN;
ALTER TABLE public.carros ADD COLUMN IF NOT EXISTS placa TEXT NOT NULL UNIQUE;
ALTER TABLE public.carros ADD COLUMN IF NOT EXISTS modelo TEXT NOT NULL;
ALTER TABLE public.carros ADD COLUMN IF NOT EXISTS ano SMALLINT NOT NULL CHECK (ano BETWEEN 1900 AND EXTRACT(YEAR FROM now())::INT + 1);
COMMIT;

